### ISSUE TITLE
A single compiler with multi target libs

### ISSUE THREAD

**Issue by abukharmeh** [Liaoshihua/code-size-reduction-gnu-toolchain#1]
Hi Liaoshihua,

Thank you for the precompiled compilers. 

I just have one small request, can we make the compiler a multi-lib one, I mean we only need a single compiler with all the libraries for various Zc* extensions, for example it should be like this
![p2_11zon](https://user-images.githubusercontent.com/24764074/180400798-b8c1cdf9-8e9f-4497-9362-45deed09f94d.jpg)
, also could you please add a compiled libc with all the subextension enabled if somebody wants to check the complete effect of Zc* extension on their code size. 

Thank you,
Ibrahim.

**Comment by Liaoshihua** [comment]
ok, i will solve it today

**Comment by Liaoshihua** [comment]
I had add it in zc_all_in_one.tar 
![image](https://user-images.githubusercontent.com/43035022/180438916-d8a2a2fa-8d75-4edb-ae9c-1447c1043d9f.png)
